# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
   git config --global user.email "piotrbiernat92@gmail.com" & git config --global user.name "pbiernat92"
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
   git checkout -b main
   echo 'This is a test' > data.txt
   git add -A
   git commit -m "deployment $(Build.BuildNumber)"
   git push --set-upstream origin main 
  displayName: Add data.txt file
  workingDirectory: $(System.DefaultWorkingDirectory)